### ISSUE TITLE
1.0.1 causes script error on startup

### ISSUE THREAD

**Issue by davidbmaier** [XertroV/tm-menu-bg-refls#1]
With today's Trackmania/Openplanet update (Sep 28th 2022), the plugin has been reported to cause in-game script errors on startup.

![grafik](https://user-images.githubusercontent.com/17618532/192830853-a6dadf40-c86f-45ba-8d9d-e9e56b5fc527.png)

It's therefore been blocked by Openplanet in the current version so it won't be loaded - it'll probably need some investigation to figure out what needs to be fixed exactly.

**Comment by XertroV** [comment]
fixed in [c04e881](https://github.com/XertroV/tm-menu-bg-refls/commit/c04e8812c92e513851faace21b36d98ad60368ca)
